baseURL: "https://sukhdeepg.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: 💾
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                # - name: Archive
                #   url: archives
                #   weight: 5
                - name: Search
                  url: search/
                  weight: 4
                - name: Tags
                  url: tags/
                  weight: 5
                - name: "Design Patterns"
                  url: "/design-patterns/"
                  weight: 1
                - name: "Annotated Papers"
                  url: "/annotated-research-papers/"
                  weight: 2
                - name: "Engineering Blogs"
                  url: "/engineering-blogs/"
                  weight: 3
                # - name: WiKi
                #   url:

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Blog"
    # author: Sukhdeep
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    # comments: false
    images: [""]

    profileMode:
        enabled: false
        title: Sukhdeep
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi there, I'm Sukhdeep 👋"
        Content: >
          I'm a software engineer specializing in backend engineering with a keen interest in system architecture.  

          I share insights and write about various engineering topics on [X](https://x.com/sgillnotes). Additionally, I maintain this blog where I write technical posts about what I've recently learned, aiming to explain concepts in a simple manner so that beginners can easily grasp them.  

          To stay updated with the latest advancements, I actively read engineering blogs and ML-related research papers.  
    socialIcons:
        - name: github
          url: "https://github.com/sukhdeepg"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        favicon: img/favicon.ico
        favicon16x16: img/favicon_16.png
        favicon32x32: img/favicon_32.png
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    witter:
        disableInlineCSS: true

permalinks:
  posts: "/design-patterns/:slug/"
  annotated-research-papers: "/annotated-research-papers/:slug/"
  engineering-blogs: "/engineering-blogs/:slug/"
